
name: Browser Tests

on:
  push:
    # branches: [ "*" ]
  pull_request:
    # branches: [ "*" ]
  workflow_dispatch:
    # branches: [ "*" ]

jobs:
  build:
    
    runs-on: ubuntu-20.04

    steps:
      
      - uses: actions/checkout@v3
    
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      # - name: Serve Files
      #   uses: Eun/http-server-action@v1
      #   with:
      #     directory: ${{ github.workspace }}
      #     port: 3000
      #     no-cache: true

      - run: npm ci --legacy-peer-deps

      - run: npm run build --if-present

      - run: npm run nightwatch

